apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "travel.fullname" . }}-frontend
  labels:
    {{ include "travel.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: {{ include "travel.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "travel.fullname" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.frontend.targetPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.frontend.liveness.path }}
              port: {{ .Values.probes.frontend.liveness.port }}
            initialDelaySeconds: {{ .Values.probes.frontend.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.frontend.liveness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.frontend.liveness.path }}
              port: {{ .Values.probes.frontend.liveness.port }}
            initialDelaySeconds: {{ .Values.probes.frontend.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.frontend.liveness.periodSeconds }}
          resources: {{ toYaml .Values.resources | nindent 10 }}
